#!/usr/bin/env python3
"""
Dump worker/src/whitelists.js from Python sources.

The Cloudflare Worker validates inbound diagnosis JSON before injecting it
into the Reflective Principle's system prompt. Geometric primitives
(trigrams, hexagram numbers, tarot numerals) are allowlist-validated;
prose is server-canonical — the worker looks up authoritative text by
the validated number/numeral and ignores whatever the frontend sent.

This script reads the Python sources of truth and emits a single
JS module so the worker bundle stays in sync with the Python.

Run:
    python3 -m tools.dump_whitelists

Output: worker/src/whitelists.js (overwritten in place).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from core.octonion import Trigram
from oracle.hexagrams import HEXAGRAM_NAMES
from oracle.interpretations import INTERPRETATIONS
from oracle.interpreter import TRIGRAM_QUALITIES, WITNESS_READINGS, DOMAIN_READINGS
from oracle.toltec import TOLTEC_HEXAGRAMS
from oracle.tarot import MAJOR_ARCANA
from oracle.runes import RUNES


OUT_PATH = ROOT / "worker" / "src" / "whitelists.js"


def js_set(values):
    items = ",\n  ".join(json.dumps(v) for v in values)
    return f"new Set([\n  {items},\n])"


def js_map_entries(entries):
    """entries = list of (key, dict) tuples. Emits new Map([...])."""
    lines = []
    for key, value in entries:
        key_js = json.dumps(key)
        fields = ", ".join(
            f"{k}: {json.dumps(v)}" for k, v in value.items()
        )
        lines.append(f"  [{key_js}, {{ {fields} }}]")
    body = ",\n".join(lines)
    return f"new Map([\n{body},\n])"


def js_map_strings(pairs):
    """pairs = list of (key, value) tuples. Emits new Map([[k, v], ...])."""
    lines = [f"  [{json.dumps(k)}, {json.dumps(v)}]" for k, v in pairs]
    body = ",\n".join(lines)
    return f"new Map([\n{body},\n])"


def main():
    trigram_elements = [t.value[1] for t in Trigram]
    trigram_meanings = [t.value[2] for t in Trigram]
    trigram_quality_strings = [v[0] for v in TRIGRAM_QUALITIES.values()]
    trigram_descriptions = [v[2] for v in TRIGRAM_QUALITIES.values()]

    king_wen_names = sorted({v[0] for v in HEXAGRAM_NAMES.values()})
    king_wen_titles = sorted({v[1] for v in HEXAGRAM_NAMES.values()})

    toltec_names = sorted({h["name"] for h in TOLTEC_HEXAGRAMS.values()})
    toltec_trad_names = sorted({h["trad_name"] for h in TOLTEC_HEXAGRAMS.values()})

    tarot_names = [MAJOR_ARCANA[i]["name"] for i in sorted(MAJOR_ARCANA)]
    tarot_numerals = [MAJOR_ARCANA[i]["numeral"] for i in sorted(MAJOR_ARCANA)]

    rune_names = [RUNES[i]["name"] for i in sorted(RUNES)]
    rune_glyphs = [RUNES[i]["glyph"] for i in sorted(RUNES)]
    rune_aetts = sorted({RUNES[i]["aett"] for i in RUNES})

    hexagram_prose_entries = []
    for n in sorted(HEXAGRAM_NAMES):
        _, _, reading = HEXAGRAM_NAMES[n]
        interp = INTERPRETATIONS.get(n, {})
        hexagram_prose_entries.append((n, {
            "reading": reading,
            "judgment": interp.get("judgment", ""),
            "image": interp.get("image", ""),
            "counsel": interp.get("counsel", ""),
        }))

    toltec_prose_entries = []
    for n in sorted(TOLTEC_HEXAGRAMS):
        h = TOLTEC_HEXAGRAMS[n]
        toltec_prose_entries.append((n, {
            "image": h.get("image", ""),
            "interp": h.get("interp", ""),
            "action": h.get("action", ""),
            "intent": h.get("intent", ""),
            "summary": h.get("summary", ""),
        }))

    tarot_prose_entries = []
    for i in sorted(MAJOR_ARCANA):
        c = MAJOR_ARCANA[i]
        tarot_prose_entries.append((c["numeral"], {
            "image": c.get("image", ""),
            "upright": c.get("upright", ""),
            "counsel": c.get("counsel", ""),
        }))

    rune_prose_entries = []
    for i in sorted(RUNES):
        r = RUNES[i]
        rune_prose_entries.append((i, {
            "image": r.get("image", ""),
            "meaning": r.get("meaning", ""),
            "counsel": r.get("counsel", ""),
        }))

    witness_text_pairs = sorted(WITNESS_READINGS.items())
    domain_text_pairs = sorted(DOMAIN_READINGS.items())

    parts = [
        "// AUTO-GENERATED by tools/dump_whitelists.py — DO NOT EDIT.",
        "// Regenerate: python3 -m tools.dump_whitelists",
        "//",
        "// Source of truth (run dumper after any change to these):",
        "//   TRIGRAM_ELEMENTS, TRIGRAM_MEANINGS  ← core/octonion.py Trigram enum",
        "//   TRIGRAM_QUALITY_STRINGS,",
        "//     TRIGRAM_DESCRIPTIONS              ← oracle/interpreter.py TRIGRAM_QUALITIES",
        "//   KING_WEN_NAMES, KING_WEN_TITLES     ← oracle/hexagrams.py HEXAGRAM_NAMES",
        "//   TOLTEC_NAMES, TOLTEC_TRAD_NAMES     ← oracle/toltec.py TOLTEC_HEXAGRAMS",
        "//   TAROT_NAMES, TAROT_NUMERALS         ← oracle/tarot.py MAJOR_ARCANA",
        "//   RUNE_NAMES, RUNE_GLYPHS, RUNE_AETTS ← oracle/runes.py RUNES",
        "//",
        "//   HEXAGRAM_PROSE  ← oracle/interpretations.py INTERPRETATIONS",
        "//                   + oracle/hexagrams.py HEXAGRAM_NAMES (reading)",
        "//   TOLTEC_PROSE    ← oracle/toltec.py TOLTEC_HEXAGRAMS",
        "//   TAROT_PROSE     ← oracle/tarot.py MAJOR_ARCANA",
        "//   RUNE_PROSE      ← oracle/runes.py RUNES",
        "//   WITNESS_TEXT    ← oracle/interpreter.py WITNESS_READINGS",
        "//   DOMAIN_TEXT     ← oracle/interpreter.py DOMAIN_READINGS",
        "//",
        "// Worker treats prose as SERVER-CANONICAL: validates the geometric",
        "// number/numeral primitive, looks up authoritative prose from the",
        "// PROSE Maps below, and substitutes in the LLM context. Inbound",
        "// prose from the frontend is ignored entirely. Defense against",
        "// prompt injection via crafted diagnosis fields.",
        "",
        f"export const TRIGRAM_ELEMENTS = {js_set(trigram_elements)};",
        "",
        f"export const TRIGRAM_MEANINGS = {js_set(trigram_meanings)};",
        "",
        f"export const TRIGRAM_QUALITY_STRINGS = {js_set(trigram_quality_strings)};",
        "",
        f"export const TRIGRAM_DESCRIPTIONS = {js_set(trigram_descriptions)};",
        "",
        f"// {len(king_wen_names)} unique romanizations across 64 hexagrams",
        f"// (some names repeat: Qian #1+#15, Bi #8+#22, Yi #27+#42, etc.)",
        f"export const KING_WEN_NAMES = {js_set(king_wen_names)};",
        "",
        f"export const KING_WEN_TITLES = {js_set(king_wen_titles)};",
        "",
        f"export const TOLTEC_NAMES = {js_set(toltec_names)};",
        "",
        f"export const TOLTEC_TRAD_NAMES = {js_set(toltec_trad_names)};",
        "",
        f"export const TAROT_NAMES = {js_set(tarot_names)};",
        "",
        f"export const TAROT_NUMERALS = {js_set(tarot_numerals)};",
        "",
        f"// 24 Elder Futhark runes (three aetts of 8).",
        f"export const RUNE_NAMES = {js_set(rune_names)};",
        "",
        f"export const RUNE_GLYPHS = {js_set(rune_glyphs)};",
        "",
        f"export const RUNE_AETTS = {js_set(rune_aetts)};",
        "",
        "// UPPERCASE_SNAKE concept names from the 3,033-entry dictionary.",
        "// Starts with a capital letter, then 0-39 more A-Z or _ chars",
        "// (matches the existing 40-char clamp ceiling).",
        "export const CONCEPT_NAME_RE = /^[A-Z][A-Z_]{0,39}$/;",
        "",
        "// ─── PROSE LOOKUP MAPS — server-canonical text ─────────────────",
        "// Keyed by the validated geometric primitive. Worker's",
        "// validateDiagnosis ignores inbound prose entirely and substitutes",
        "// the canonical text below before rendering the LLM context.",
        "",
        f"// 64 King Wen hexagrams: reading + judgment + image + counsel.",
        f"export const HEXAGRAM_PROSE = {js_map_entries(hexagram_prose_entries)};",
        "",
        f"// 64 Toltec hexagrams: image + interp + action + intent + summary.",
        f"export const TOLTEC_PROSE = {js_map_entries(toltec_prose_entries)};",
        "",
        f"// 22 Major Arcana cards keyed by Roman numeral (matches",
        f"// tarot.{{presenting,medicine}}.numeral): image + upright + counsel.",
        f"export const TAROT_PROSE = {js_map_entries(tarot_prose_entries)};",
        "",
        f"// 24 Elder Futhark runes keyed by rune number 1-24 (matches",
        f"// runes.{{presenting,medicine}}.number): image + meaning + counsel.",
        f"export const RUNE_PROSE = {js_map_entries(rune_prose_entries)};",
        "",
        f"// 4 witness-state readings keyed by witness_state (dissolution,",
        f"// partial, preserved, tension).",
        f"export const WITNESS_TEXT = {js_map_strings(witness_text_pairs)};",
        "",
        f"// 4 domain readings keyed by presenting.dominant (spatial,",
        f"// temporal, relational, personal).",
        f"export const DOMAIN_TEXT = {js_map_strings(domain_text_pairs)};",
        "",
    ]

    output = "\n".join(parts)
    OUT_PATH.write_text(output)
    raw_kb = len(output.encode("utf-8")) / 1024
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} — {raw_kb:.1f} KiB raw")
    print(f"  HEXAGRAM_PROSE: {len(hexagram_prose_entries)} entries")
    print(f"  TOLTEC_PROSE:   {len(toltec_prose_entries)} entries")
    print(f"  TAROT_PROSE:    {len(tarot_prose_entries)} entries")
    print(f"  RUNE_PROSE:     {len(rune_prose_entries)} entries")
    print(f"  WITNESS_TEXT:   {len(witness_text_pairs)} entries")
    print(f"  DOMAIN_TEXT:    {len(domain_text_pairs)} entries")


if __name__ == "__main__":
    main()
